language: java
jdk:
  - oraclejdk11
env:
  matrix:
    - ELASTICSEARCH_VERSION=7.10.1
    - ELASTICSEARCH_VERSION=7.10.0
    - ELASTICSEARCH_VERSION=7.9.3
    - ELASTICSEARCH_VERSION=7.9.2
    - ELASTICSEARCH_VERSION=7.9.1
    - ELASTICSEARCH_VERSION=7.9.0
    - ELASTICSEARCH_VERSION=7.8.1
    - ELASTICSEARCH_VERSION=7.8.0
    - ELASTICSEARCH_VERSION=7.7.1
    - ELASTICSEARCH_VERSION=7.7.0

script: "mvn clean install -Delasticsearch.version=${ELASTICSEARCH_VERSION}"

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: target/releases/*.zip
  skip_cleanup: true
  on:
    tags: true