# Build and test zentity for each supported version of OpenSearch whenever pushing a commit or submitting a pull request.
name: Commit
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - "zentity-*.*.*"
      - "zentity-*.*.*-*"
  pull_request:
    branches:
      - '**'
    tags-ignore:
      - "zentity-*.*.*"
      - "zentity-*.*.*-*"

jobs:
  build:
    strategy:

      # Attempt to run all tests.
      fail-fast: false

      # Build and test zentity for each version of OpenSearch that its APIs support.
      matrix:
        opensearch:
          - 1.2.4

    # Use the latest LTS OS.
    runs-on: ubuntu-20.04

    steps:

      # Checkout the repository.
      # Uses: https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Configure the JDK.
      # Uses: https://github.com/actions/setup-java
      # OpenSearch compatibility: https://opensearch.org/docs/latest/opensearch/install/compatibility/
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Cache Maven packages.
      # Uses: https://github.com/actions/cache
      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Build and test zentity for a given version of OpenSearch.
      - name: Build and test
        env:
          OPENSEARCH_VERSION: ${{ matrix.opensearch }}
        run: mvn --batch-mode clean install "-Dopensearch.version=$OPENSEARCH_VERSION" --file pom.xml