# Build and test zentity for each supported version of Elasticsearch whenever pushing a commit or submitting a pull request.
name: Commit
on:
  - push
  - pull_request

jobs:
  build:
    strategy:

      # Attempt to run all tests.
      fail-fast: false

      # Build and test zentity for each version of Elasticsearch that its APIs support.
      matrix:
        elasticsearch:
          - 7.10.2
          - 7.10.1
          - 7.10.0
          - 7.9.3
          - 7.9.2
          - 7.9.3
          - 7.8.1
          - 7.8.0
          - 7.7.1
          - 7.7.0

    # Use the latest LTS OS.
    runs-on: ubuntu-20.04

    steps:

      # Checkout the repository.
      # Uses: https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Configure the JDK.
      # Uses: https://github.com/actions/setup-java
      # Elasticsearch JVM support matrix: https://www.elastic.co/support/matrix#matrix_jvm
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Cache Maven packages.
      # Uses: https://github.com/actions/cache
      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Build and test zentity for a given version of Elasticsearch.
      - name: Build and test
        env:
          ELASTICSEARCH_VERSION: ${{ matrix.elasticsearch }}
        run: mvn --batch-mode clean install "-Delasticsearch.version=$ELASTICSEARCH_VERSION" --file pom.xml